### ISSUE TITLE
Update csv under /data to latest version?

### ISSUE THREAD

**Issue by tomwenseleers** [MagnusBook/flunet-scraper#2]
Thanks for the nice scraper! Was just wondering if you would mind to rerun it to have the latest csv available under data? I'm just asking in the context of an analysis of worldwide excess mortality I am doing and I would like to include influenza activity if possible, and it would be handy if right now I could just point to your csv on github in my R script...

cheers & many thanks in advance!

**Comment by MagnusBook** [comment]
Sorry for not getting back to you sooner, I have been out of action for a while. Great to hear that they have made the CSV files available! I guess this makes this repository a bit irrelevant. I will add the links to the README file in case anyone else stumbles upon the project.
